#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
export ZPREZTODIR="$HOME/.dotfiles/zprezto"

# Source Prezto.
if [[ -s "${ZPREZTODIR}/init.zsh" ]]; then
  source "${ZPREZTODIR}/init.zsh"
fi

# Customize to your needs...
export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"

export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
