#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
export ZPREZTODIR="$HOME/.dotfiles/zprezto"

# Source Prezto.
if [[ -s "${ZPREZTODIR}/init.zsh" ]]; then
  source "${ZPREZTODIR}/init.zsh"
fi

# Customize to your needs...
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"
